/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package routine7;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rAZU
 */

public class Add_admin extends JFrame {

    /**
     * Creates new form Add_admin
     */
   // JFrame f1;
    JDialog f;
    Connection Add_Admin_Con;
    Statement Add_Admin_State;
    ResultSet Add_Admin_Rs;
    
    JLabel error;
    
    public Add_admin() {
        
        connect();
       // f1 = new JFrame("Admin Registration Form");
        
       /* f.setLocation(350, 5);
        f.setMaximizedBounds(new java.awt.Rectangle(350,5, 620, 690));
        f.setMaximumSize(new java.awt.Dimension(620, 690));
        f.setMinimumSize(new java.awt.Dimension(620, 690));
      */
        f = new JDialog(this, rootPaneCheckingEnabled);
        f.setTitle("Admin Registration");
        f.setBounds(360,17,613,680);        
        f.setResizable(false);
        
        
        
      //  f.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        initComponents();
        
        
        
        jLabel_empty_field_checker.setVisible(false);
        jLabel_Password_Test.setVisible(false);
        jLabel_Repet_Password_Test.setVisible(false);
        jLabel_Username_Test.setVisible(false);
        jLabel_ID_Test.setVisible(false);
        jLabel4.setVisible(false);
        jPanel2.setVisible(false);
        jLabel3.setVisible(false);
      //  jPanel1.add(error);
        f.add(jPanel1);
        f.show();
        
   /*     jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                try
                {                  
                    String add=jTextField1.getText().trim();                
                    String sql = "select Admin_Number from Table_Admin_Number where Admin_Number='"+add+"'";
                    Add_Admin_Rs = Add_Admin_State.executeQuery(sql);
                    
                    int count = 0;
                    while(Add_Admin_Rs.next())
                    {
                        count++;
                    }
                   
                    if(count==1)
                    {
                     
                        jLabel3.setVisible(false);
                        JOptionPane.showMessageDialog(null,"Admin Number found in the Admin List" + "\n" +         "You have permission to be an Admin.");                                
                        jButton1.setVisible(false);
                        jLabel4.setVisible(true);
                        jPanel2.setVisible(true);          
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(null,"Admin Number not found in the Admin List     ");
                       jTextField1.setText(null);
                       
                     
                       jLabel3.setVisible(true);
                     //  jLabel3.setText("** Please enter correct Admin Number or Contact to your Author to get Correct Admin Number ** ");
                    }
                        
                    
                    
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                
            }
        });*/
        
    }
    
    
   

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Full_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_School = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Position = new javax.swing.JTextField();
        jTextField_UserName = new javax.swing.JTextField();
        jTextField_Password = new javax.swing.JTextField();
        jTextField_Phone_Number = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jButton_Submit = new javax.swing.JButton();
        jLabel_Username_Test = new javax.swing.JLabel();
        jLabel_Repet_Password_Test = new javax.swing.JLabel();
        jLabel_ID_Test = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Repet_Password = new javax.swing.JTextField();
        jTextField_ID_Number = new javax.swing.JTextField();
        jLabel_Password_Test = new javax.swing.JLabel();
        jLabel_empty_field_checker = new javax.swing.JLabel();
        jComboBox1_Gender = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximizedBounds(new java.awt.Rectangle(350, 5, 620, 690));
        setMaximumSize(new java.awt.Dimension(620, 690));
        setMinimumSize(new java.awt.Dimension(620, 690));
        setPreferredSize(new java.awt.Dimension(620, 690));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(620, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 690));

        jButton_Check.setFont(new java.awt.Font("Rod", 1, 19)); // NOI18N
        jButton_Check.setText("ChecK");
        jButton_Check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vani", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Admin Registration");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        jLabel2.setText("Admin Number");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField1.setText("Enter Admin Number Given by Author");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("** Please enter correct Admin Number or Contact to your Author to get your Admin Number inserted ** ");

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), null, null, new java.awt.Color(153, 153, 153))));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel5.setText("Full Name         :");

        jTextField_Full_Name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Full_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel6.setText("ID. no.                :");

        jLabel7.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel7.setText("Dept. / School   :");

        jTextField_School.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_School.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SchoolActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel8.setText("Position             :");

        jLabel9.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel9.setText("UserName         :");

        jLabel10.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel10.setText("Password           :");

        jLabel11.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel11.setText("Repet Password :");

        jLabel12.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel12.setText("Gender               :");

        jLabel13.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel13.setText("Phone no.           :");

        jLabel14.setFont(new java.awt.Font("Vani", 0, 19)); // NOI18N
        jLabel14.setText("E-Mail                :");

        jTextField_Position.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField_UserName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UserNameActionPerformed(evt);
            }
        });

        jTextField_Password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PasswordActionPerformed(evt);
            }
        });

        jTextField_Phone_Number.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        jButton_Submit.setFont(new java.awt.Font("Rod", 1, 17)); // NOI18N
        jButton_Submit.setForeground(new java.awt.Color(0, 153, 51));
        jButton_Submit.setText("SubmiT");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jLabel_Username_Test.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Username_Test.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Username_Test.setText("*already exists");

        jLabel_Repet_Password_Test.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Repet_Password_Test.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Repet_Password_Test.setText("*didn't match");

        jLabel_ID_Test.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_ID_Test.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_ID_Test.setText("*already exists");

        jLabel15.setText("                            .");

        jTextField_Repet_Password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Repet_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Repet_PasswordActionPerformed(evt);
            }
        });

        jTextField_ID_Number.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_ID_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ID_NumberActionPerformed(evt);
            }
        });

        jLabel_Password_Test.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Password_Test.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Password_Test.setText("*try another");

        jLabel_empty_field_checker.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_empty_field_checker.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_empty_field_checker.setText("jLabel16");

        jComboBox1_Gender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox1_Gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboBox1_Gender.setToolTipText("");
        jComboBox1_Gender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_GenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(jTextField_UserName)
                                    .addComponent(jTextField_Phone_Number, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Repet_Password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Username_Test)
                                    .addComponent(jLabel_Repet_Password_Test)
                                    .addComponent(jLabel_Password_Test)))
                            .addComponent(jComboBox1_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Full_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_ID_Number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_ID_Test))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_School, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Position, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_empty_field_checker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Submit)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Full_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_ID_Test)
                    .addComponent(jTextField_ID_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_School, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Username_Test))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Password_Test)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_Repet_Password_Test)
                    .addComponent(jTextField_Repet_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Submit)
                            .addComponent(jLabel_empty_field_checker))
                        .addContainerGap())))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Fillup the Form carefully. All fields must have to be filled up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Check))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Add_Admin");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   /*  private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
         try
         {JOptionPane.showMessageDialog(null,"User Found, Access Granted");
             String add=jTextField1.getText().trim();
             String sql = "select Admin_Number from Table_Admin_Number where Admin_Number='"+add+"'";
             Add_Admin_Rs = Add_Admin_State.executeQuery(sql);
         }
         catch(SQLException e)
         {
             
         }
      
         
         
    }   
 */   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_SchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SchoolActionPerformed

    private void jTextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UserNameActionPerformed

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PasswordActionPerformed

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
        // TODO add your handling code here:
        try
        {
      //      System.out.println("start");
            String admin_number=jTextField1.getText().trim();
            System.out.println(admin_number);
            String full_name=jTextField_Full_Name.getText().trim();
     //       System.out.println(full_name);
        //    String gender=jTextField_Gender.getText().trim();
            String gender=jComboBox1_Gender.getSelectedItem().toString().trim();
            String id_number=jTextField_ID_Number.getText().trim();
            String department=jTextField_School.getText().trim();
            String position=jTextField_Position.getText().trim();
            String username=jTextField_UserName.getText().trim();
            String password1=jTextField_Password.getText().trim();
            String password=jTextField_Repet_Password.getText().trim();
            String phone_number=jTextField_Phone_Number.getText().trim();
            String email=jTextField_Email.getText().trim();
            
        //    System.out.println("mid");
            
             
            //ID. no. TEST 
            int c=0;
            String id_test = "select ID_Number from TableLogIn where ID_Number='"+id_number+"'";
            Add_Admin_Rs = Add_Admin_State.executeQuery(id_test);
            System.out.println("ID executed");      
            int count1 = 0;
            while(Add_Admin_Rs.next())        
            {
                count1++;        
            }           
                   
            if(count1>=1)
            {
                jLabel_ID_Test.setVisible(true);
                c=c+1;
            }   
            else
            {
                jLabel_ID_Test.setVisible(false);
            }
            
            
            //UserName TEST           
            String username_test = "select UserName from TableLogIn where UserName='"+username+"'";
            Add_Admin_Rs = Add_Admin_State.executeQuery(username_test);
            System.out.println("Username executed");      
            int count2 = 0;
            while(Add_Admin_Rs.next())        
            {
                count2++;        
            }           
                   
            if(count2>=1)
            {
                jLabel_Username_Test.setVisible(true);
                c=c+1;
            }   
            else
            {
                jLabel_Username_Test.setVisible(false);
            }
             
            
            //Password TEST           
            String password_test = "select Password from TableLogIn where Password='"+password1+"'";
            Add_Admin_Rs = Add_Admin_State.executeQuery(password_test);
            System.out.println("Password executed");      
            int count3 = 0;
            while(Add_Admin_Rs.next())        
            {
                count3++;        
            }           
                   
            if(count3>=1)
            {
               jLabel_Password_Test.setVisible(true);
               c=c+1;
            }   
            else
            {
                jLabel_Password_Test.setVisible(false);
            }
            
            
            //Repet Password TEST           
            int result=password.compareTo(password1);
            if(result==0)
            {
                jLabel_Repet_Password_Test.setVisible(false);
            }
            else
            {
                jLabel_Repet_Password_Test.setVisible(true);
                c=c+1;
            }
                    
            
            int length_full_name=full_name.length();
            int length_gender=gender.length(); 
            int length_id_number=id_number.length();
            int length_department=department.length();
            int length_position=position.length();
            int length_username=username.length();
            int length_password1=password1.length();
            int length_password=password.length();
            int length_phone_number=phone_number .length();
            int length_email=email.length();
            
            int d=0;
            if(length_full_name==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Full Name' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_gender==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Gender' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_id_number==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'ID. no.' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_department==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Dept./School' is empty");
                jLabel_empty_field_checker.setVisible(true); 
            }
                 
            if(length_position==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Position' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_username==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'UserName' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_password1==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Password' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_password==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Repet Password' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_phone_number==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'Phone Number' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
                 
            if(length_email==0)
            {
                d=d+1;
                jLabel_empty_field_checker.setText("** Field 'E-Mail' is empty");
                jLabel_empty_field_checker.setVisible(true);
            }
            
            if(d>1)
            {
                jLabel_empty_field_checker.setText("** More than 1  Fields are empty");
                jLabel_empty_field_checker.setVisible(true);
            }
             
            if(d==0)jLabel_empty_field_checker.setVisible(false);       
                    
      //  String sql = "select Admin_Number from Table_Admin_Number where Admin_Number='"+add+"'";
      //  Add_Admin_Rs = Add_Admin_State.executeQuery(sql);
       // Add_Admin_Con.execute("insert into TableLogIn (Name,S_ID,S_age,T_ID)values('"+full_name+"','13.02.04.005',27,1)");
        /*if(c==0 && d==0)
          {
               Add_Admin_State.execute("insert into TableLogIn (Admin_Number,Admin_Full_Name,Gender,ID_Number,"
                    + "Department,Position,UserName,Password,Phone_Number,E_mail)values('"+admin_number+"',"
                    + "'"+full_name+"','"+gender+"','"+id_number+"','"+department+"','"+position+"',"
                    + "'"+username+"','"+password+"','"+phone_number+"','"+email+"')");
            
        */if(c==0 && d==0)
          {
                Add_Admin_State.execute("insert into TableLogIn(Admin_Number,Admin_Full_Name,Gender,ID_Number,Department,Position,UserName,Password,Phone_Number,E_mail)values('"+admin_number+"',"
                    + "'"+full_name+"','"+gender+"','"+id_number+"','"+department+"','"+position+"',"
                    + "'"+username+"','"+password+"','"+phone_number+"','"+email+"')");
                
                Add_Admin_State.execute("insert into Table_Admin_Number_Check (Admin_Number)values('"+admin_number+"')");
         ///   System.out.println("EXc");
            
             JOptionPane.showMessageDialog(null, "                 -:  CONGRATULATIONS  :-    "+"\n"+"New Admin Account Created Successfully.");
             f.setVisible(false);
          }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jTextField_Repet_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Repet_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Repet_PasswordActionPerformed

    private void jTextField_ID_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ID_NumberActionPerformed
        // TODO add your handling code here:
        try
        {
            String id=jTextField_ID_Number.getText().trim();
                     
            String id_test = "select ID_Number from TableLogIn where ID_Number='"+id+"'";
            Add_Admin_Rs = Add_Admin_State.executeQuery(id_test);
              System.err.println("ID OK");      
                    int count = 0;
                    while(Add_Admin_Rs.next())
                    {
                        count++;
                    }
                   
                    if(count==1)
                    {
                     JOptionPane.showMessageDialog(null, "ok");
                    }   
                    else
                    {
                       jLabel_ID_Test.setVisible(false);
                     //  jLabel3.setText("** Please enter correct Admin Number or Contact to your Author to get Correct Admin Number ** ");
                    }
                        
                    
                    
                }
        
                catch(Exception e)
                {
             
                }
    }//GEN-LAST:event_jTextField_ID_NumberActionPerformed

    private void jButton_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CheckActionPerformed
        // TODO add your handling code here:
        
        try
                {                  
                    String add=jTextField1.getText().trim();                
                    String sql = "select Admin_Number from Table_Admin_Number where Admin_Number='"+add+"'";
                    Add_Admin_Rs = Add_Admin_State.executeQuery(sql);
                    
                    int count = 0;
                    while(Add_Admin_Rs.next())
                    {
                        count++;
                    }
                    
                    
                    String add2=jTextField1.getText().trim();                
                    String sql2 = "select Admin_Number from Table_Admin_Number_Check where Admin_Number='"+add+"'";
                    Add_Admin_Rs = Add_Admin_State.executeQuery(sql2);
                    
                    int count2 = 0;
                    while(Add_Admin_Rs.next())
                    {
                        count2++;
                    }
                    
                    if(count2>0)JOptionPane.showMessageDialog(null,"Sorry  ! !" + "\n" + "This Admin Number have been used before." + "\n" + "Please enter new Admin Number.");
                   
                    else if(count==1 && count2==0)
                    {
                     
                        jLabel3.setVisible(false);
                        JOptionPane.showMessageDialog(null,"Admin Number found in the Admin List." + "\n" +         "You have permission to be an Admin.");                                
                        jButton_Check.setVisible(false);
                        jLabel4.setVisible(true);
                        jPanel2.setVisible(true);          
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(null,"Admin Number not found in the Admin List     ");
                       jTextField1.setText(null);
                       
                     
                       jLabel3.setVisible(true);
                     //  jLabel3.setText("** Please enter correct Admin Number or Contact to your Author to get Correct Admin Number ** ");
                    }
                        
                    
                    
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                
            
        
        
    }//GEN-LAST:event_jButton_CheckActionPerformed

    private void jComboBox1_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_GenderActionPerformed

   
    public  void connect()
    {
        
       try
        {
          //  String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
           // Class.forName(driver);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            
            String AccessFileName="D:/Razu's Document/SD-II ( LAB )/Routine7/src/routine7/LogInData";
            
            String db1 = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + AccessFileName + ".accdb;";
            Add_Admin_Con = DriverManager.getConnection(db1, "", "");
            Add_Admin_State = Add_Admin_Con.createStatement();
            
            System.out.println("hii");
        }
        catch(Exception ex)
        {
            
        }
                         
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //      new Add_admin().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Check;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JComboBox jComboBox1_Gender;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ID_Test;
    private javax.swing.JLabel jLabel_Password_Test;
    private javax.swing.JLabel jLabel_Repet_Password_Test;
    private javax.swing.JLabel jLabel_Username_Test;
    private javax.swing.JLabel jLabel_empty_field_checker;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Full_Name;
    private javax.swing.JTextField jTextField_ID_Number;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_Phone_Number;
    private javax.swing.JTextField jTextField_Position;
    private javax.swing.JTextField jTextField_Repet_Password;
    private javax.swing.JTextField jTextField_School;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables

}
