/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package routine7;

import java.awt.Button;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static org.eclipse.persistence.expressions.ExpressionOperator.maximum;
import static org.eclipse.persistence.expressions.ExpressionOperator.minimum;

/**
 *
 * @author rAZU
 */
public class Author extends javax.swing.JFrame {

    JDialog f;
    Connection Data_Con;
    Statement Data_State;
    ResultSet Data_Resultset;
    PreparedStatement Data_Pre_State;
    

    public Author() {
        
        connect();
       
      //  JFrame f;
        f = new JDialog(this, rootPaneCheckingEnabled);
        f.setTitle("Author Workplace");
        f.setBounds(360,17,613,680);        
        f.setResizable(false);
      // f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
  
                
        initComponents();
        
        jLayeredPane_Update_Account.setVisible(false);
        jPanel_Add_Admin_Number.setVisible(false);
        jLabel_Update_A_AC_Checker.setVisible(false);
     //   panel_Add_Admin_Number.add(button_Ad_Generator);
    //    panel_Add_Admin_Number.add(label_Ad_Number);
        
    //    f.add(panel_Add_Admin_Number);
        f.add(jPanel_Down);
        f.show();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Down = new javax.swing.JPanel();
        jPanel_Down_up1 = new javax.swing.JPanel();
        jLabel_Author_Area = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button_Update_Admin_Account = new java.awt.Button();
        button_Add_Admin_Number = new java.awt.Button();
        jPanel_down_panel_up_up2 = new javax.swing.JPanel();
        jLayeredPane_Update_Account = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Up_Ad_Full_name = new javax.swing.JTextField();
        jTextField_Up_Ad_Phone_Number = new javax.swing.JTextField();
        jTextField_Up_Ad_Position = new javax.swing.JTextField();
        jTextField_Up_Ad_UserName = new javax.swing.JTextField();
        jTextField_Up_Ad_Password = new javax.swing.JTextField();
        button_Update_Admin_Account_Done = new java.awt.Button();
        jLabel_Update_A_AC_Checker = new javax.swing.JLabel();
        button_AC_Up_Done = new java.awt.Button();
        jPanel_Add_Admin_Number = new javax.swing.JPanel();
        button_Admin_Number_Generator = new java.awt.Button();
        jLabel_Generated_Admin_Number = new javax.swing.JLabel();
        jTextField_Generated_Admin_Number = new javax.swing.JTextField();
        button_Add_This_Admin_Number = new java.awt.Button();
        button_Add_Admin_Number_Done = new java.awt.Button();
        button_Show_Admin_Number_List = new java.awt.Button();
        button_Author_LogOut = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(613, 680));

        jPanel_Down.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_Down_up1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Down_up1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Author_Area.setFont(new java.awt.Font("DialogInput", 1, 25)); // NOI18N
        jLabel_Author_Area.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Author_Area.setText(" Author Area");
        jLabel_Author_Area.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 153, 51));
        button1.setLabel(" Remove Admin");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button_Update_Admin_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Update_Admin_Account.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        button_Update_Admin_Account.setForeground(new java.awt.Color(0, 153, 51));
        button_Update_Admin_Account.setLabel("Update Account");
        button_Update_Admin_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Update_Admin_AccountActionPerformed(evt);
            }
        });

        button_Add_Admin_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Add_Admin_Number.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        button_Add_Admin_Number.setForeground(new java.awt.Color(0, 153, 51));
        button_Add_Admin_Number.setLabel("Add Admin Num.");
        button_Add_Admin_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Add_Admin_NumberActionPerformed(evt);
            }
        });

        jPanel_down_panel_up_up2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel_down_panel_up_up2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        jLabel1.setText("Full Name :");

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        jLabel2.setText("Phone Number :");

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        jLabel3.setText("Position :");

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        jLabel4.setText("UserName :");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        jLabel5.setText("Password :");

        jTextField_Up_Ad_Full_name.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jTextField_Up_Ad_Full_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Up_Ad_Full_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField_Up_Ad_Full_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Up_Ad_Full_nameActionPerformed(evt);
            }
        });

        jTextField_Up_Ad_Phone_Number.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jTextField_Up_Ad_Phone_Number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Up_Ad_Phone_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField_Up_Ad_Position.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jTextField_Up_Ad_Position.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Up_Ad_Position.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField_Up_Ad_UserName.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jTextField_Up_Ad_UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Up_Ad_UserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextField_Up_Ad_Password.setFont(new java.awt.Font("DialogInput", 0, 15)); // NOI18N
        jTextField_Up_Ad_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Up_Ad_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        button_Update_Admin_Account_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Update_Admin_Account_Done.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        button_Update_Admin_Account_Done.setForeground(new java.awt.Color(0, 102, 0));
        button_Update_Admin_Account_Done.setLabel("UpdatE");
        button_Update_Admin_Account_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Update_Admin_Account_DoneActionPerformed(evt);
            }
        });

        jLabel_Update_A_AC_Checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Update_A_AC_Checker.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Update_A_AC_Checker.setText("jLabel6");

        button_AC_Up_Done.setBackground(new java.awt.Color(0, 204, 204));
        button_AC_Up_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_AC_Up_Done.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        button_AC_Up_Done.setForeground(new java.awt.Color(240, 240, 240));
        button_AC_Up_Done.setLabel("Done");
        button_AC_Up_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AC_Up_DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane_Update_AccountLayout = new javax.swing.GroupLayout(jLayeredPane_Update_Account);
        jLayeredPane_Update_Account.setLayout(jLayeredPane_Update_AccountLayout);
        jLayeredPane_Update_AccountLayout.setHorizontalGroup(
            jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_Update_AccountLayout.createSequentialGroup()
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jLayeredPane_Update_AccountLayout.createSequentialGroup()
                        .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Up_Ad_Full_name, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jTextField_Up_Ad_Phone_Number)
                            .addComponent(jTextField_Up_Ad_Position)
                            .addComponent(jTextField_Up_Ad_UserName)
                            .addComponent(jTextField_Up_Ad_Password)))
                    .addGroup(jLayeredPane_Update_AccountLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_Update_A_AC_Checker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Update_Admin_Account_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(button_AC_Up_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane_Update_AccountLayout.setVerticalGroup(
            jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_Update_AccountLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Up_Ad_Full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Up_Ad_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Up_Ad_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Up_Ad_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Up_Ad_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jLayeredPane_Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Update_Admin_Account_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Update_A_AC_Checker))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_Update_AccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_AC_Up_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane_Update_Account.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jTextField_Up_Ad_Full_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jTextField_Up_Ad_Phone_Number, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jTextField_Up_Ad_Position, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jTextField_Up_Ad_UserName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jTextField_Up_Ad_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(button_Update_Admin_Account_Done, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(jLabel_Update_A_AC_Checker, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Update_Account.setLayer(button_AC_Up_Done, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel_Add_Admin_Number.setBackground(new java.awt.Color(0, 153, 51));

        button_Admin_Number_Generator.setBackground(new java.awt.Color(0, 153, 153));
        button_Admin_Number_Generator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Admin_Number_Generator.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Admin_Number_Generator.setForeground(new java.awt.Color(204, 204, 204));
        button_Admin_Number_Generator.setLabel("Admin Number Generator");
        button_Admin_Number_Generator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Admin_Number_GeneratorActionPerformed(evt);
            }
        });

        jLabel_Generated_Admin_Number.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        jLabel_Generated_Admin_Number.setText("Generated Admin Number :");

        jTextField_Generated_Admin_Number.setEditable(false);
        jTextField_Generated_Admin_Number.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Generated_Admin_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        button_Add_This_Admin_Number.setBackground(new java.awt.Color(0, 153, 153));
        button_Add_This_Admin_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Add_This_Admin_Number.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Add_This_Admin_Number.setForeground(new java.awt.Color(204, 204, 204));
        button_Add_This_Admin_Number.setLabel("Add This Admin Number ");
        button_Add_This_Admin_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Add_This_Admin_NumberActionPerformed(evt);
            }
        });

        button_Add_Admin_Number_Done.setBackground(new java.awt.Color(0, 153, 153));
        button_Add_Admin_Number_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Add_Admin_Number_Done.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        button_Add_Admin_Number_Done.setForeground(new java.awt.Color(204, 204, 204));
        button_Add_Admin_Number_Done.setLabel("Done");
        button_Add_Admin_Number_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Add_Admin_Number_DoneActionPerformed(evt);
            }
        });

        button_Show_Admin_Number_List.setBackground(new java.awt.Color(0, 153, 153));
        button_Show_Admin_Number_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Show_Admin_Number_List.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Show_Admin_Number_List.setForeground(new java.awt.Color(204, 204, 204));
        button_Show_Admin_Number_List.setLabel("Show Admin Number List");
        button_Show_Admin_Number_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Show_Admin_Number_ListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Add_Admin_NumberLayout = new javax.swing.GroupLayout(jPanel_Add_Admin_Number);
        jPanel_Add_Admin_Number.setLayout(jPanel_Add_Admin_NumberLayout);
        jPanel_Add_Admin_NumberLayout.setHorizontalGroup(
            jPanel_Add_Admin_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Add_Admin_NumberLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_Add_Admin_Number_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_Add_Admin_NumberLayout.createSequentialGroup()
                .addGroup(jPanel_Add_Admin_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Admin_Number_Generator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Add_Admin_NumberLayout.createSequentialGroup()
                        .addComponent(jLabel_Generated_Admin_Number)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Generated_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_Add_This_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Show_Admin_Number_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel_Add_Admin_NumberLayout.setVerticalGroup(
            jPanel_Add_Admin_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Add_Admin_NumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_Admin_Number_Generator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel_Add_Admin_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Generated_Admin_Number)
                    .addComponent(jTextField_Generated_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(button_Add_This_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(button_Show_Admin_Number_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(button_Add_Admin_Number_Done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel_down_panel_up_up2Layout = new javax.swing.GroupLayout(jPanel_down_panel_up_up2);
        jPanel_down_panel_up_up2.setLayout(jPanel_down_panel_up_up2Layout);
        jPanel_down_panel_up_up2Layout.setHorizontalGroup(
            jPanel_down_panel_up_up2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_down_panel_up_up2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane_Update_Account)
                .addContainerGap())
            .addGroup(jPanel_down_panel_up_up2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_down_panel_up_up2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Add_Admin_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_down_panel_up_up2Layout.setVerticalGroup(
            jPanel_down_panel_up_up2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_down_panel_up_up2Layout.createSequentialGroup()
                .addComponent(jLayeredPane_Update_Account)
                .addContainerGap())
            .addGroup(jPanel_down_panel_up_up2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_down_panel_up_up2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Add_Admin_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        button_Author_LogOut.setBackground(new java.awt.Color(204, 0, 0));
        button_Author_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Author_LogOut.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        button_Author_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        button_Author_LogOut.setLabel("LogOut");
        button_Author_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Author_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Down_up1Layout = new javax.swing.GroupLayout(jPanel_Down_up1);
        jPanel_Down_up1.setLayout(jPanel_Down_up1Layout);
        jPanel_Down_up1Layout.setHorizontalGroup(
            jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_down_panel_up_up2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_Down_up1Layout.createSequentialGroup()
                .addGroup(jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Down_up1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_Author_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Down_up1Layout.createSequentialGroup()
                        .addComponent(button_Update_Admin_Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Add_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_Down_up1Layout.createSequentialGroup()
                        .addComponent(jLabel_Author_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_Down_up1Layout.setVerticalGroup(
            jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Down_up1Layout.createSequentialGroup()
                .addGroup(jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Author_Area)
                    .addComponent(button_Author_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel_Down_up1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_Add_Admin_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Update_Admin_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel_down_panel_up_up2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_DownLayout = new javax.swing.GroupLayout(jPanel_Down);
        jPanel_Down.setLayout(jPanel_DownLayout);
        jPanel_DownLayout.setHorizontalGroup(
            jPanel_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Down_up1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_DownLayout.setVerticalGroup(
            jPanel_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Down_up1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Up_Ad_Full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Up_Ad_Full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Up_Ad_Full_nameActionPerformed

    private void button_Update_Admin_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Update_Admin_AccountActionPerformed
        // TODO add your handling code here:
        
        jPanel_Add_Admin_Number.setVisible(false);
        jLayeredPane_Update_Account.setVisible(true);
        
     //   new NewJFrame().setVisible(true);
        
    }//GEN-LAST:event_button_Update_Admin_AccountActionPerformed

    private void button_Add_Admin_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Add_Admin_NumberActionPerformed
        // TODO add your handling code here:
        
        jLayeredPane_Update_Account.setVisible(false);
        jPanel_Add_Admin_Number.setVisible(true);
        
    }//GEN-LAST:event_button_Add_Admin_NumberActionPerformed

    private void button_Admin_Number_GeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Admin_Number_GeneratorActionPerformed
        // TODO add your handling code here:
        
      /*  Random rn = new Random();
        int n = 90000 - (10000) + 1;
        int i = rn.nextInt() % n;
        int randomNum =  10000 + i;
       */
        
        
        int randomNum1 = 97 + (int)(Math.random()*25); 
        char c1=(char)randomNum1;
        String str1= Character.toString(c1);
        
        int randomNum2 = 97 + (int)(Math.random()*25); 
        char c2=(char)randomNum2;
        String str2= Character.toString(c2);
        
        int randomNum3 = 10000 + (int)(Math.random()*90000); 
        
        
        int randomNum4 = 97 + (int)(Math.random()*25); 
        char c3=(char)randomNum4;
        String str3=Character.toString(c3);
       
        String fs=str1+str2+randomNum3+str3;
        
        System.out.println(fs);
        
        jTextField_Generated_Admin_Number.setText(fs);
        
    }//GEN-LAST:event_button_Admin_Number_GeneratorActionPerformed

    private void button_Add_This_Admin_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Add_This_Admin_NumberActionPerformed
        // TODO add your handling code here:
        
        String Ad_Number=jTextField_Generated_Admin_Number.getText().trim();
        System.out.println(Ad_Number);
        
        if(Ad_Number.length()==0)JOptionPane.showMessageDialog(null," Admin  Number  has  not  been  Generated  yet"+"\n"+"Please  generate  Admin  Number  and  hit  Add");
        else
        {
        // ADMIN NUMBER EXISTENCE check
        try
        {
            String admin_number_test = "select Admin_Number from Table_Admin_Number where Admin_Number='"+Ad_Number+"'";
            Data_Resultset = Data_State.executeQuery(admin_number_test);
            System.out.println("admin number executed");      
            int count = 0;
            while(Data_Resultset.next())        
            {
                count++;        
            }           
                   
            if(count>0)
            {
               JOptionPane.showMessageDialog(null,"       Admin Number Already exists"+"\n"+"Please reGenarate and hit add again");
            }   
            else
            {
                try
                {
                    Data_State.execute("insert into Table_Admin_Number(Admin_Number)values('"+Ad_Number+"')");
            
                    JOptionPane.showMessageDialog(null, "Admin Number Successfully added"+"\n"+"         to the Admin Number List ");
            
                }catch(Exception ex){
            
                    JOptionPane.showMessageDialog(null,ex);
                }
                
            }
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,ex);
        }
        } 
    }//GEN-LAST:event_button_Add_This_Admin_NumberActionPerformed

    private void button_Show_Admin_Number_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Show_Admin_Number_ListActionPerformed
        // TODO add your handling code here:
        new Admin_Number_List();
        
    }//GEN-LAST:event_button_Show_Admin_Number_ListActionPerformed

    private void button_Add_Admin_Number_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Add_Admin_Number_DoneActionPerformed
        // TODO add your handling code here:
        
        jPanel_Add_Admin_Number.setVisible(false);
        jTextField_Generated_Admin_Number.setText(null);
    }//GEN-LAST:event_button_Add_Admin_Number_DoneActionPerformed

    private void button_Update_Admin_Account_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Update_Admin_Account_DoneActionPerformed
        // TODO add your handling code here:
        
        String full_mame=jTextField_Up_Ad_Full_name.getText().trim();
        String phone_number=jTextField_Up_Ad_Phone_Number.getText().trim();
        String position=jTextField_Up_Ad_Position.getText().trim();
        String username=jTextField_Up_Ad_UserName.getText().trim();
        String password=jTextField_Up_Ad_Password.getText().trim();
        
        int count1=0;
        
        if(full_mame.length()==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** field Full Name is empty");
            count1++;
            
        }
        
        if(phone_number.length()==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** field Phone Number is empty");
            count1++;
            
        }
        
        if(position.length()==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** field Position is empty");
            count1++;
            
        }
        
        if(username.length()==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** field UserName is empty");
            count1++;
            
        }
        
        if(password.length()==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** field Password is empty");
            count1++;
            
        }
        
        if(count1>1)
        {
            jLabel_Update_A_AC_Checker.setVisible(true);
            jLabel_Update_A_AC_Checker.setText("** more than 1 fields are empty");
            count1++;
            
        }
        
        else if(count1==0)
        {
            jLabel_Update_A_AC_Checker.setVisible(false);
            try
            {
                
                 Data_State.execute("update TableAuthor set Full_Name='"+full_mame+"', Phone_Number='"+phone_number+"' , Position='"+position+"' , UserName='"+username+"' , Password='"+password+"' where ID=1");
                 
                 JOptionPane.showMessageDialog(null, " Account Successfully Updated ");
                        
                 jTextField_Up_Ad_Full_name.setText(null);
                 jTextField_Up_Ad_Phone_Number.setText(null);
                 jTextField_Up_Ad_Position.setText(null);
                 jTextField_Up_Ad_UserName.setText(null);
                 jTextField_Up_Ad_Password.setText(null);
                       
                
            }catch(Exception ex){
                
                JOptionPane.showMessageDialog(null, ex);
                
            }
            
        }
        
    }//GEN-LAST:event_button_Update_Admin_Account_DoneActionPerformed

    private void button_Author_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Author_LogOutActionPerformed
        // TODO add your handling code here:
        
        f.setVisible(false);
    }//GEN-LAST:event_button_Author_LogOutActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        jLayeredPane_Update_Account.setVisible(false);
        jPanel_Add_Admin_Number.setVisible(false);
        new Remove_Admin();
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button_AC_Up_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AC_Up_DoneActionPerformed
        // TODO add your handling code here:
        
        
         jTextField_Up_Ad_Full_name.setText(null);
         jTextField_Up_Ad_Password.setText(null);
         jTextField_Up_Ad_Phone_Number.setText(null);
         jTextField_Up_Ad_Position.setText(null);
         jTextField_Up_Ad_UserName.setText(null);
         
         jLayeredPane_Update_Account.setVisible(false);
        
    }//GEN-LAST:event_button_AC_Up_DoneActionPerformed

    
    public  void connect()
    {
        
       try
        {
          //  String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
           // Class.forName(driver);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            
            String AccessFileName="D:/Razu's Document/SD-II ( LAB )/Routine7/src/routine7/LogInData";
            
            String db1 = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + AccessFileName + ".accdb;";
            Data_Con = DriverManager.getConnection(db1, "", "");
            Data_State =Data_Con.createStatement();
            
            System.out.println("hii");
        }
        catch(Exception ex)
        {
            
        }
                         
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Author().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button_AC_Up_Done;
    private java.awt.Button button_Add_Admin_Number;
    private java.awt.Button button_Add_Admin_Number_Done;
    private java.awt.Button button_Add_This_Admin_Number;
    private java.awt.Button button_Admin_Number_Generator;
    private java.awt.Button button_Author_LogOut;
    private java.awt.Button button_Show_Admin_Number_List;
    private java.awt.Button button_Update_Admin_Account;
    private java.awt.Button button_Update_Admin_Account_Done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Author_Area;
    private javax.swing.JLabel jLabel_Generated_Admin_Number;
    private javax.swing.JLabel jLabel_Update_A_AC_Checker;
    private javax.swing.JLayeredPane jLayeredPane_Update_Account;
    private javax.swing.JPanel jPanel_Add_Admin_Number;
    private javax.swing.JPanel jPanel_Down;
    private javax.swing.JPanel jPanel_Down_up1;
    private javax.swing.JPanel jPanel_down_panel_up_up2;
    private javax.swing.JTextField jTextField_Generated_Admin_Number;
    private javax.swing.JTextField jTextField_Up_Ad_Full_name;
    private javax.swing.JTextField jTextField_Up_Ad_Password;
    private javax.swing.JTextField jTextField_Up_Ad_Phone_Number;
    private javax.swing.JTextField jTextField_Up_Ad_Position;
    private javax.swing.JTextField jTextField_Up_Ad_UserName;
    // End of variables declaration//GEN-END:variables
}
