/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package routine7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author rAZU
 */
public class Author_LogIN extends javax.swing.JFrame {

    JDialog f;
    
    Connection Data_Con;
    Statement Data_State;
    ResultSet Data_Resultset;
    
    
    public Author_LogIN() {
        
        connect();
        
        f = new JDialog(this, rootPaneCheckingEnabled);
        f.setTitle("Author Security");       
        f.setBounds(370, 100, 650, 450);
        f.setResizable(false);
        
        
        initComponents();
        
        jLabel_empty_field_checker.setVisible(false);
        f.add(jPanel_Author_LogIn_Down);
        f.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Author_LogIn_Down = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Author_UserName = new javax.swing.JPanel();
        jTextField_Author_UserName = new javax.swing.JTextField();
        jPanel_Author_Password = new javax.swing.JPanel();
        jTextField_Author_Password = new javax.swing.JPasswordField();
        button_Author_LogIN = new java.awt.Button();
        jLabel_Author_LogIn = new javax.swing.JLabel();
        button_Author_LogIn_Cancel = new java.awt.Button();
        jLabel_empty_field_checker = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Author_LogIn_Down.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Author_LogIn_Down.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/routine7/secure-cloud-computing1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel_Author_UserName.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Author_UserName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UserName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 17), new java.awt.Color(0, 255, 255))); // NOI18N

        jTextField_Author_UserName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Author_UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Author_UserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField_Author_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Author_UserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Author_UserNameLayout = new javax.swing.GroupLayout(jPanel_Author_UserName);
        jPanel_Author_UserName.setLayout(jPanel_Author_UserNameLayout);
        jPanel_Author_UserNameLayout.setHorizontalGroup(
            jPanel_Author_UserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Author_UserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Author_UserName)
                .addContainerGap())
        );
        jPanel_Author_UserNameLayout.setVerticalGroup(
            jPanel_Author_UserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Author_UserNameLayout.createSequentialGroup()
                .addComponent(jTextField_Author_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel_Author_Password.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Author_Password.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 17), new java.awt.Color(0, 255, 255))); // NOI18N

        jTextField_Author_Password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_Author_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Author_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel_Author_PasswordLayout = new javax.swing.GroupLayout(jPanel_Author_Password);
        jPanel_Author_Password.setLayout(jPanel_Author_PasswordLayout);
        jPanel_Author_PasswordLayout.setHorizontalGroup(
            jPanel_Author_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Author_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Author_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Author_PasswordLayout.setVerticalGroup(
            jPanel_Author_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Author_PasswordLayout.createSequentialGroup()
                .addComponent(jTextField_Author_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        button_Author_LogIN.setBackground(new java.awt.Color(204, 204, 204));
        button_Author_LogIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Author_LogIN.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        button_Author_LogIN.setForeground(new java.awt.Color(0, 153, 153));
        button_Author_LogIN.setLabel("LogIn");
        button_Author_LogIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Author_LogINActionPerformed(evt);
            }
        });

        jLabel_Author_LogIn.setFont(new java.awt.Font("Viner Hand ITC", 1, 37)); // NOI18N
        jLabel_Author_LogIn.setForeground(new java.awt.Color(0, 255, 255));
        jLabel_Author_LogIn.setText("Author LogIN");

        button_Author_LogIn_Cancel.setBackground(new java.awt.Color(204, 204, 204));
        button_Author_LogIn_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Author_LogIn_Cancel.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        button_Author_LogIn_Cancel.setForeground(new java.awt.Color(0, 153, 153));
        button_Author_LogIn_Cancel.setLabel("Cancel");
        button_Author_LogIn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Author_LogIn_CancelActionPerformed(evt);
            }
        });

        jLabel_empty_field_checker.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_empty_field_checker.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_empty_field_checker.setText("jLabel2");

        javax.swing.GroupLayout jPanel_Author_LogIn_DownLayout = new javax.swing.GroupLayout(jPanel_Author_LogIn_Down);
        jPanel_Author_LogIn_Down.setLayout(jPanel_Author_LogIn_DownLayout);
        jPanel_Author_LogIn_DownLayout.setHorizontalGroup(
            jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel_Author_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel_Author_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                                .addComponent(button_Author_LogIn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_Author_LogIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_empty_field_checker)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Author_LogIn)
                .addGap(173, 173, 173))
        );
        jPanel_Author_LogIn_DownLayout.setVerticalGroup(
            jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                .addComponent(jLabel_Author_LogIn)
                .addGroup(jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel_Author_LogIn_DownLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel_Author_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_Author_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_Author_LogIn_DownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_Author_LogIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_Author_LogIn_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_empty_field_checker)
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Author_LogIn_Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Author_LogIn_Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Author_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Author_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Author_UserNameActionPerformed

    private void button_Author_LogINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Author_LogINActionPerformed
        // TODO add your handling code here:
        
        try
               {
                   
                  int test=0;
                          
                  String user = jTextField_Author_UserName.getText().trim();
                  String pass = jTextField_Author_Password.getText().trim();
                  
                  int length_user=user.length();
                  int length_pass=pass.length();
                  
                  if(length_user==0)
                  {
                      jLabel_empty_field_checker.setVisible(true);
                      jLabel_empty_field_checker.setText("** UserName is empty ");
                      test++;
                      System.out.println(+test);
                  }
                  
                  if(length_pass==0)
                  {
                      jLabel_empty_field_checker.setVisible(true);
                      jLabel_empty_field_checker.setText("** Password is empty ");
                      test++;
                      System.out.println(+test);
                  }
                   
                  if(length_user==0 && length_pass==0)
                  {
                      jLabel_empty_field_checker.setVisible(true);
                      jLabel_empty_field_checker.setText("** Both UserName and Password are empty ");
                      test++;
                      System.out.println(+test);
                  }
                  
                  else if(test==0)
                  {
                      jLabel_empty_field_checker.setVisible(false);
                  
                  
                      String sql = "select UserName,Password from TableAuthor where UserName='"+user+"'and Password ='"+pass+"'";
                      Data_Resultset = Data_State.executeQuery(sql);
                   
                // JOptionPane.showMessageDialog(null,"User Found, Access Granted");
                   
                      int count = 0;
                      while(Data_Resultset.next())
                      {
                          count++;
                      }
                   
                      if(count>=1)
                      {
                     //     JOptionPane.showMessageDialog(null,"User Found, Access Granted");
                                
                   
                          f.setVisible(false);
                          new Author();
                      
                   
                      }
                        
                      else
                      {
                          JOptionPane.showMessageDialog(null,"User not Found !"
                                  + "  Please Enter Currect UserName or Password");
                          jTextField_Author_Password.setText(null);
                      }
                  }                                      
               }
               catch(Exception ex)
               {
                   
               }
        
        
    }//GEN-LAST:event_button_Author_LogINActionPerformed

    private void button_Author_LogIn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Author_LogIn_CancelActionPerformed
        // TODO add your handling code here:
        
        f.setVisible(false);
    }//GEN-LAST:event_button_Author_LogIn_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
     public  void connect()
    {
        
       try
        {
          //  String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
           // Class.forName(driver);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            
            String AccessFileName="D:/Razu's Document/SD-II ( LAB )/Routine7/src/routine7/LogInData";
            
            String db1 = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + AccessFileName + ".accdb;";
            Data_Con = DriverManager.getConnection(db1, "", "");
            Data_State =Data_Con.createStatement();
            
            System.out.println("hii");
        }
        catch(Exception ex)
        {
            
        }
                         
    } 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Author_LogIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Author_LogIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Author_LogIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Author_LogIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Author_LogIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_Author_LogIN;
    private java.awt.Button button_Author_LogIn_Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Author_LogIn;
    private javax.swing.JLabel jLabel_empty_field_checker;
    private javax.swing.JPanel jPanel_Author_LogIn_Down;
    private javax.swing.JPanel jPanel_Author_Password;
    private javax.swing.JPanel jPanel_Author_UserName;
    private javax.swing.JPasswordField jTextField_Author_Password;
    private javax.swing.JTextField jTextField_Author_UserName;
    // End of variables declaration//GEN-END:variables
}
