/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package routine7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author rAZU
 */
public class Exit_Confirmation extends javax.swing.JFrame {

    Connection Data_Con;
    Statement Data_State;
    ResultSet Data_Resultset;
    
    JDialog f;
    
    
    public Exit_Confirmation() {
        
        connect();
        
        f = new JDialog(this, rootPaneCheckingEnabled);
        f.setTitle("Quit Confirmation");       
        f.setBounds(500,200,450,230);        
        f.setResizable(false);
        f.setDefaultCloseOperation(0);
        
        
        initComponents();
        
        f.add(jPanel_Exit_Confirmation);
        f.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Exit_Confirmation = new javax.swing.JPanel();
        jLabel_Exit_Conformation = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Exit_Confirmation.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Exit_Confirmation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel_Exit_Conformation.setFont(new java.awt.Font("DialogInput", 1, 30)); // NOI18N
        jLabel_Exit_Conformation.setForeground(new java.awt.Color(51, 255, 255));
        jLabel_Exit_Conformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Exit_Conformation.setText(" Are you sure to QUIT  ?");

        button1.setBackground(new java.awt.Color(153, 153, 153));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        button1.setLabel("YES");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(153, 153, 153));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        button2.setLabel("NO");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Exit_ConfirmationLayout = new javax.swing.GroupLayout(jPanel_Exit_Confirmation);
        jPanel_Exit_Confirmation.setLayout(jPanel_Exit_ConfirmationLayout);
        jPanel_Exit_ConfirmationLayout.setHorizontalGroup(
            jPanel_Exit_ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Exit_ConfirmationLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(jPanel_Exit_ConfirmationLayout.createSequentialGroup()
                .addComponent(jLabel_Exit_Conformation)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_Exit_ConfirmationLayout.setVerticalGroup(
            jPanel_Exit_ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Exit_ConfirmationLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel_Exit_Conformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel_Exit_ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Exit_Confirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Exit_Confirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try 
        {
          //  Data_State.execute("update Table_Anim set anim='no' where ID=1");
            
        } catch (Exception ex) {
            
            Logger.getLogger(Exit_Confirmation.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        f.setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       // f.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    

   
    public  void connect()
    {
        
       try
        {
          //  String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
           // Class.forName(driver);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            
            String AccessFileName="D:/Razu's Document/SD-II ( LAB )/Routine7/src/routine7/LogInData";
            
            String db1 = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + AccessFileName + ".accdb;";
            Data_Con = DriverManager.getConnection(db1, "", "");
            Data_State =Data_Con.createStatement();
            
            System.out.println("hii");
        }
        catch(Exception ex)
        {
            
        }
                         
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exit_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exit_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exit_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exit_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exit_Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel_Exit_Conformation;
    private javax.swing.JPanel jPanel_Exit_Confirmation;
    // End of variables declaration//GEN-END:variables
}
