/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package routine7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rAZU
 */
public class Routine_Manage extends javax.swing.JFrame {

    
   // JFrame f;
    JDialog f;

    Connection Data_Con;
    Statement Data_State;
    Statement Data_State1,Data_State2,Data_State3;
    ResultSet Data_Resultset;
    ResultSet Data_Resultset1,Data_Resultset2,Data_Resultset3;
    PreparedStatement Data_Pre_State;
    
    public Routine_Manage() {
        
        connect();
      //  JOptionPane.showM
        f = new JDialog(this, rootPaneCheckingEnabled);
        f.setTitle("Routine Management");       
        f.setBounds(7,10,1350,692);        
        f.setResizable(false);
        
      //  f.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        initComponents();
      
        Update_Routine();
        System.out.println("Rou");
        
        jLabel4.setVisible(false);
        jLabel2.setVisible(false);
        f.add(jPanel1);
        f.show();
        
    }
    
    
    private void Update_Routine()
    {
        try
        {
           System.out.println("Start UP");
           String sql_Data="Select Day2, Class_1st, Class_2nd, Class_3rd, Class_4th, Class_5th ,Class_6th , Class_7th , "
                   + "Class_8th , Class_9th , Class_10th , Class_11th , Class_12th  from Routine13__2_1__C1";
          // String sql_Data="Select 1st Class, 2nd Class, 3rd Class, 4th Class, 5th Class, 6th Class, 7th Class from Routine13__2_1__C1";
          // Data_State.execute("Select * from Routine13#2_1(C-1)");  
            System.out.println("Mid UPMethod");
       //    Data_Resultset= Data_State.getResultSet();  
       //    System.out.println("End UPMethod");
           Data_Pre_State=Data_Con.prepareStatement(sql_Data);
           
           System.out.println("Mid 1.1 UPMethod");
           Data_Resultset=Data_Pre_State.executeQuery();
           
           System.out.println("Mid2 UPMethod");
           jTable1.setModel(DbUtils.resultSetToTableModel(Data_Resultset));
           System.out.println("End UPMethod");
           while(Data_Resultset.next())
            	{
                	System.out.println("Name: "+Data_Resultset.getString("Admin_Number"));
                }
            
            
        }catch(Exception ex){
           // JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        button_Update = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_Add_Data = new java.awt.Button();
        button1 = new java.awt.Button();
        jComboBox1_Class_Number = new javax.swing.JComboBox();
        textField_New_Value = new javax.swing.JTextField();
        jComboBox1_Day = new javax.swing.JComboBox();
        jComboBox_Day2 = new javax.swing.JComboBox();
        jComboBox_Class_Number2 = new javax.swing.JComboBox();
        textField_Course_Name = new javax.swing.JTextField();
        textField_Time_to_Time = new javax.swing.JTextField();
        textField_Room_No = new javax.swing.JTextField();
        button_Routine_Manage_Delete = new java.awt.Button();
        jComboBox_Data_Type = new javax.swing.JComboBox();
        textField_Teacher_Name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED))));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 646));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Rod", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Update Data");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), null, null));

        label1.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label1.setText("Class:");

        label2.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        label2.setPreferredSize(new java.awt.Dimension(60, 20));
        label2.setText("Data Type:");

        label3.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label3.setText("Day:");

        label4.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        label4.setText("New Value:");

        button_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Update.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Update.setForeground(new java.awt.Color(0, 102, 0));
        button_Update.setLabel("UpdatE");
        button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Rod", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setLabelFor(jPanel2);
        jLabel3.setText("Add/Delete Data");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), null, null));

        label5.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label5.setText("Day:");

        label6.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label6.setText("Class:");

        label7.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label7.setText("Time-Time:");

        label8.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label8.setText("Course Name:");

        label9.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label9.setText("Room No.:");

        label10.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        label10.setText("Teacher's Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Rod", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("N.B-To delete data just select ");

        jLabel6.setFont(new java.awt.Font("Rod", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Day & Class and hit Delete");

        button_Add_Data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Add_Data.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Add_Data.setForeground(new java.awt.Color(0, 102, 0));
        button_Add_Data.setLabel("Add");
        button_Add_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Add_DataActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 102, 0));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("DonE");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jComboBox1_Class_Number.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBox1_Class_Number.setMaximumRowCount(5);
        jComboBox1_Class_Number.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class_1st", "Class_2nd", "Class_3rd", "Class_4th", "Class_5th", "Class_6th", "Class_7th", "Class_8th", "Class_9th", "Class_10th", "Class_11th", "Class_12th", "Class_13th" }));
        jComboBox1_Class_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1_Class_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textField_New_Value.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField_New_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_New_Value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBox1_Day.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBox1_Day.setMaximumRowCount(5);
        jComboBox1_Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));
        jComboBox1_Day.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1_Day.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1_Day.setFocusTraversalPolicyProvider(true);

        jComboBox_Day2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBox_Day2.setMaximumRowCount(5);
        jComboBox_Day2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));
        jComboBox_Day2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Day2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox_Class_Number2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBox_Class_Number2.setMaximumRowCount(5);
        jComboBox_Class_Number2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class_1st", "Class_2nd", "Class_3rd", "Class_4th", "Class_5th", "Class_6th", "Class_7th", "Class_8th", "Class_9th", "Class_10th", "Class_11th", "Class_12th", "Class_13th" }));
        jComboBox_Class_Number2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Class_Number2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textField_Course_Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField_Course_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Course_Name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textField_Course_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Course_NameActionPerformed(evt);
            }
        });

        textField_Time_to_Time.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField_Time_to_Time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Time_to_Time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textField_Time_to_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Time_to_TimeActionPerformed(evt);
            }
        });

        textField_Room_No.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField_Room_No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Room_No.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textField_Room_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Room_NoActionPerformed(evt);
            }
        });

        button_Routine_Manage_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Routine_Manage_Delete.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        button_Routine_Manage_Delete.setForeground(new java.awt.Color(0, 102, 0));
        button_Routine_Manage_Delete.setLabel("Delete");
        button_Routine_Manage_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Routine_Manage_DeleteActionPerformed(evt);
            }
        });

        jComboBox_Data_Type.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBox_Data_Type.setMaximumRowCount(3);
        jComboBox_Data_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Time", "Subject Name", "Room no.", "Teacher Name" }));
        jComboBox_Data_Type.setAutoscrolls(true);
        jComboBox_Data_Type.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Data_Type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textField_Teacher_Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField_Teacher_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Teacher_Name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textField_Teacher_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Teacher_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1_Class_Number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1_Day, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_New_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jComboBox_Data_Type, 0, 0, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_Day2, 0, 97, Short.MAX_VALUE)
                                .addComponent(jComboBox_Class_Number2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_Course_Name)
                                .addComponent(textField_Time_to_Time)
                                .addComponent(textField_Room_No))
                            .addComponent(textField_Teacher_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Routine_Manage_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Add_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1_Class_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_Data_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_New_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jComboBox_Day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jComboBox_Class_Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textField_Time_to_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textField_Course_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField_Room_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textField_Teacher_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(button_Add_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_Routine_Manage_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Day", "1st Class", "2nd Class", "3rd Class", "4th Class", "5th Class", "6th Class", "7th Class", "8th Class", "9th Class", "10th Class", "11th Class", "12th  Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setPreferredSize(new java.awt.Dimension(975, 603));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UpdateActionPerformed
        // TODO add your handling code here:
        
        try
        {
          //  Data_State.execute("update TableTest set Gender=30 where ID=72");
            
          //  String Class_Number=textField_Class_Number.getText().trim();
            String Class_Number=jComboBox1_Class_Number.getSelectedItem().toString().trim();
            String New_Value=textField_New_Value.getText().trim();
            String Day=jComboBox1_Day.getSelectedItem().toString().trim();
            String Data_Type=jComboBox_Data_Type.getSelectedItem().toString().trim();
         //   String Old_Value=textField_Old_Value.getText().trim();
            
 
            int length_Day=Day.length();
            int length_New_Value=New_Value.length();
            
            
            
            String type=null;
            int serial_no=0;
            if("Time".equals(Data_Type))
            {
                serial_no=1;
                type="Class_Time";
            }
            
            if("Subject Name".equals(Data_Type))
            {
                serial_no=2;
                type="Subject";
            }
            
            if("Room no.".equals(Data_Type))
            {
                serial_no=3;
                type="Room_Number";
            }
            
            if("Teacher Name".equals(Data_Type))
            {
                serial_no=4;
                type="Teacher_Name";
            }
           
            
            int count=0;
     
            if(length_Day==0)
            {
                count=count+1;
                jLabel2.setText("** field 'Day' is empty");
                jLabel2.setVisible(true);
            }
            
            if(length_New_Value==0)
            {
                count=count+1;
                jLabel2.setText("** field 'New Value' is empty");
                jLabel2.setVisible(true);
            }
            
            if(count>1)
            {
                jLabel2.setText("** more than 1 fields are empty");
                jLabel2.setVisible(true);
            }
            
            if (count==0)
            {
                jLabel2.setVisible(false);
                
              
                int exist=0;
                Data_State.execute("select "+Class_Number+" from Routine13__2_1__C1 where  Day='"+Day+"' and Serial_no=2");
                Data_Resultset = Data_State.getResultSet();

                while(Data_Resultset.next())
                {
                    String value=Data_Resultset.getString(Class_Number);

                    int length_value=value.length();
                    if(length_value>0) exist=exist+1;

                }

                if(exist==0)JOptionPane.showMessageDialog(null, "Field is empty."+"\n"+"Select the field that exists data");
                
                
                else
                {
                
                    Data_State.execute("update Routine13__2_1__C1 set "+Class_Number+"='"+New_Value+"' where Serial_no="+serial_no+"and Day='"+Day+"'");
                    Data_State.execute("update Routine13__2_1__C1_no_2 set "+type+"='"+New_Value+"' where Day='"+Day+"' and Class_Number='"+Class_Number+"'");

                    JOptionPane.showMessageDialog(null, "Data Successfully Updated");
                    Update_Routine();
                
                
                 }
            } 
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
                
        
    }//GEN-LAST:event_button_UpdateActionPerformed

    private void button_Add_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Add_DataActionPerformed
      
        String Day2=jComboBox_Day2.getSelectedItem().toString().trim();
        String Class_Number2=jComboBox_Class_Number2.getSelectedItem().toString().trim();
        String Time_to_Time=textField_Time_to_Time.getText().trim();
        String Course_Name=textField_Course_Name.getText().trim();
        String Room_No=textField_Room_No.getText().trim();
        String Teacher_Name=textField_Teacher_Name.getText().trim();
        
        int length_Time_to_Time=Time_to_Time.length();
        int length_Course_Name=Course_Name.length();
        int length_Room_No=Room_No.length();
        int length_Teacher_Name=Teacher_Name.length();
        
        int count=0;
        if(length_Time_to_Time==0)
        {
            count=count+1;
            jLabel4.setText("** field 'Time-Time' is empty");
            jLabel4.setVisible(true);
        }
        if(length_Course_Name==0)
        {
            count=count+1;
            jLabel4.setText("** field 'Course Name' is empty");
            jLabel4.setVisible(true);
        }
        if(length_Room_No==0)
        {
            count=count+1;
            jLabel4.setText("** field 'Room No' is empty");
            jLabel4.setVisible(true);
        }
        if(length_Teacher_Name==0)
        {
            count=count+1;
            jLabel4.setText("** field 'Teacher Name' is empty");
            jLabel4.setVisible(true);
        }
        if(count>1)
        {
            jLabel4.setText("** more than 1 fields are empty");
            jLabel4.setVisible(true);
        }
        if (count==0)
        {
            jLabel4.setVisible(false);
           
            try
            {
                int exist2=0;
                Data_State.execute("select "+Class_Number2+" from Routine13__2_1__C1 where  Day='"+Day2+"' and Serial_no=2");
                Data_Resultset = Data_State.getResultSet();

                while(Data_Resultset.next())
                {
                    String value=Data_Resultset.getString(Class_Number2);

                    int length_value=value.length();
                    if(length_value>0) exist2=exist2+1;

                }

                if(exist2>0)JOptionPane.showMessageDialog(null, "Data already exists");
            
                else
                {
              
                    Data_State.execute("update Routine13__2_1__C1 set "+Class_Number2+"='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
                    Data_State.execute("update Routine13__2_1__C1 set "+Class_Number2+"='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
                    Data_State.execute("update Routine13__2_1__C1 set "+Class_Number2+"='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
                    Data_State.execute("update Routine13__2_1__C1 set "+Class_Number2+"='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");


                    Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='"+Class_Number2+"'");
                    Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='"+Class_Number2+"'");
                    Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='"+Class_Number2+"'");
                    Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='"+Class_Number2+"'");    

                   //  Data_State.execute("update Routine13 set Time='6746746' where ID=1");

                    JOptionPane.showMessageDialog(null, " Data Added successfully to  "+Class_Number2+"");
                    Update_Routine();
               
                 
                } 
              
             }catch(Exception ex){
              
               JOptionPane.showMessageDialog(null, ex);
              
             }
                                // unused_Update_Code();          
        }
        
    }//GEN-LAST:event_button_Add_DataActionPerformed

    
    
    void unused_Update_Code()
{
    
                /*    {
            
            
            int Class1=Class_Number2.compareTo("Class_1st");
            int Class2=Class_Number2.compareTo("Class_2nd");
            int Class3=Class_Number2.compareTo("Class_3rd");
            int Class4=Class_Number2.compareTo("Class_4th");
            int Class5=Class_Number2.compareTo("Class_5th");
            int Class6=Class_Number2.compareTo("Class_6th");
            int Class7=Class_Number2.compareTo("Class_7th");
            int Class8=Class_Number2.compareTo("Class_8th");
            int Class9=Class_Number2.compareTo("Class_9th");
            int Class10=Class_Number2.compareTo("Class_10th");
            int Class11=Class_Number2.compareTo("Class_11th");
            int Class12=Class_Number2.compareTo("Class_12th");
            int Class13=Class_Number2.compareTo("Class_13th");
            
            int exist= 0;
            
            /*    if(Class1==0)
            {
            Data_State.execute("select Class_1st from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_1st");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_1st");
            }
            
            else if(Class2==0)
            {
            Data_State.execute("select Class_2nd from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_2nd");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_2nd");
            }
            
            else if(Class3==0)
            {
            Data_State.execute("select Class_3rd from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_3rd");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_3rd");
            
            }
            
            else if(Class4==0)
            {
            Data_State.execute("select Class_4th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_4th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_4th");
            
            }
            
            else if(Class5==0)
            {
            Data_State.execute("select Class_5th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_5th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_5th");
            
            }
            
            else if(Class6==0)
            {
            Data_State.execute("select Class_6th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_6th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_6th");
            
            }
            
            else if(Class7==0)
            {
            Data_State.execute("select Class_7th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_7th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_7th");
            
            }
            
            if(Class8==0)
            {
            Data_State2.execute("select Class_8th from Routine13__2_1__C1 where ID=9 and Day='"+Day2+"'");
            Data_Resultset2 =Data_State2.getResultSet();
            
            while(Data_Resultset2.next())
            {
            String GetTime=Data_Resultset2.getString("Class_8th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_8th");
            
            }
            
            /*     else if(Class9==0)
            {
            Data_State.execute("select Class_9th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_9th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_9th");
            
            }
            
            else if(Class10==0)
            {
            Data_State.execute("select Class_10th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_10th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_10th");
            
            }
            
            else if(Class11==0)
            {
            Data_State.execute("select Class_11th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_11th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_11th");
            
            }
            
            else if(Class12==0)
            {
            Data_State.execute("select Class_12th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_12th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_12th");
            
            }
            
            else//(Class13==0)
            {
            Data_State.execute("select Class_13th from Routine13__2_1__C1 where Serial_no=1 and Day='"+Day2+"'");
            Data_Resultset = Data_State.getResultSet();
            
            while(Data_Resultset.next())
            {
            String GetTime=Data_Resultset.getString("Class_13th");
            
            int length_GetTime=GetTime.length();
            if(length_GetTime>0) exist=exist+1;
            
            }
            
            if(exist!=0)JOptionPane.showMessageDialog(null, "Class already Exists in  " +Day2 +"  Class_13th");
            
            }
            */
            /*         int valid=0;
            //    if(exist!=0)valid=valid+1;
            
            if(Class1==0 || Class2==0 || Class3==0 || Class4==0 || Class5==0 || Class6==0 || Class7==0 || Class8==0 || Class9==0 || Class10==0 || Class11==0 || Class12==0 || Class13==0)
            {
            valid=valid+1;
            
            }
            else JOptionPane.showInternalMessageDialog(null, "!! Class Name is Wrong !!");
            
            
            
            if(Class1==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_1st='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_1st='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_1st='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_1st='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_1st'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_1st'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_1st'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_1st'");
            
            //  Data_State.execute("update Routine13 set Time='6746746' where ID=1");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_1st");
            Update_Routine();
            
            }
            
            if(Class2==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_2nd='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_2nd='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_2nd='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_2nd='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_2nd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_2nd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_2nd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_2nd'");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_2nd");
            Update_Routine();
            }
            
            if(Class3==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_3rd='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_3rd='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_3rd='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_3rd='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_3rd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_3rd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_3rd'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_3rd'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_3rd");
            Update_Routine();
            }
            
            if(Class4==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_4th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_4th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_4th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_4th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_4th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_4th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_4th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_4th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_4th");
            Update_Routine();
            }
            
            if(Class5==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_5th='"+Time_to_Time+"' where Day='"+Day2+"' and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_5th='"+Course_Name+"' where Day='"+Day2+"' and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_5th='"+Room_No+"' where Day='"+Day2+"'and  Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_5th='"+Teacher_Name+"' where Day='"+Day2+"' and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_5th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_5th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_5th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_5th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_5th");
            Update_Routine();
            }
            
            if(Class6==0 && valid>0)
            {
            // Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+New_Value+"' where Class_6th='"+Old_Value+"'and Day='"+Day+"'");
            Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_6th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_6th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_6th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_6th'");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_6th");
            Update_Routine();
            }
            
            if(Class7==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_7th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_7th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_7th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_7th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_7th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_7th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_7th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_7th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_7th");
            Update_Routine();;
            }
            
            if(Class8==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_8th='"+Time_to_Time+"' where Day='"+Day2+"' and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_8th='"+Course_Name+"' where Day='"+Day2+"' and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_8th='"+Room_No+"' where Day='"+Day2+"' and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_8th='"+Teacher_Name+"' where Day='"+Day2+"' and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_8th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_8th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_8th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_8th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_8th");
            Update_Routine();
            }
            
            if(Class9==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_9th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_9th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_9th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_9th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_9th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_9th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_9th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_9th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_9th");
            Update_Routine();
            }
            
            if(Class10==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_10th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_10th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_10th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_10th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_10th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_10th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_10th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_10th'");
            
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_10th");
            Update_Routine();
            }
            
            if(Class11==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_11th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_11th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_11th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_11th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_11th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_11th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_11th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_11th'");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_11th");
            Update_Routine();
            }
            
            if(Class12==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_12th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_12th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_12th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_12th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_12th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_12th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_12th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_12th'");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_12th");
            Update_Routine();
            }
            
            if(Class13==0 && valid>0)
            {
            Data_State.execute("update Routine13__2_1__C1 set Class_13th='"+Time_to_Time+"' where Day='"+Day2+"'and Serial_no=1");
            Data_State.execute("update Routine13__2_1__C1 set Class_13th='"+Course_Name+"' where Day='"+Day2+"'and Serial_no=2");
            Data_State.execute("update Routine13__2_1__C1 set Class_13th='"+Room_No+"' where Day='"+Day2+"'and Serial_no=3");
            Data_State.execute("update Routine13__2_1__C1 set Class_13th='"+Teacher_Name+"' where Day='"+Day2+"'and Serial_no=4");
            
            
            Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='"+Time_to_Time+"' where Day='"+Day2+"' and Class_Number='Class_13th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Subject='"+Course_Name+"' where Day='"+Day2+"'and Class_Number='Class_13th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Room_Number='"+Room_No+"' where Day='"+Day2+"'and Class_Number='Class_13th'");
            Data_State.execute("update Routine13__2_1__C1_no_2 set Teacher_Name='"+Teacher_Name+"' where Day='"+Day2+"'and Class_Number='Class_13th'");
            
            JOptionPane.showMessageDialog(null, " Data Added successfully to  Class_13th");
            Update_Routine();
            
            
            // and Day='"+Day+"'
            
            */ 
    
    
    
}
    
    
    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        f.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    private void textField_Course_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Course_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Course_NameActionPerformed

    private void textField_Time_to_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Time_to_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Time_to_TimeActionPerformed

    private void textField_Room_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Room_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Room_NoActionPerformed

    private void button_Routine_Manage_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Routine_Manage_DeleteActionPerformed
        // TODO add your handling code here:
        
        String Day3=jComboBox_Day2.getSelectedItem().toString().trim();
        String Class_Number3=jComboBox_Class_Number2.getSelectedItem().toString().trim();
        
        
        try
        {
        
                Data_State.execute("update Routine13__2_1__C1 set "+Class_Number3+"='' where Day='"+Day3+"'and Serial_no=1");
                Data_State.execute("update Routine13__2_1__C1 set "+Class_Number3+"='' where Day='"+Day3+"'and Serial_no=2");
                Data_State.execute("update Routine13__2_1__C1 set "+Class_Number3+"='' where Day='"+Day3+"'and Serial_no=3");
                Data_State.execute("update Routine13__2_1__C1 set "+Class_Number3+"='' where Day='"+Day3+"'and Serial_no=4");

                Data_State.execute("update Routine13__2_1__C1_no_2 set Class_Time='', Subject='', Room_Number='', Teacher_Name='' where Class_Number='"+Class_Number3+"' and Day='"+Day3+"'");

              //  JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_1st");
                jLabel4.setVisible(false);
                Update_Routine();
                        
                     
                                                                      //       unused_Delete_code();   
           
            
         }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
         }
        
    }//GEN-LAST:event_button_Routine_Manage_DeleteActionPerformed

    void unused_Delete_code()
    {
        
        /*         if(Class2==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_2nd='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_2nd='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_2nd='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_2nd='' where Day='"+Day3+"'and Serial_no=4");
                        
                      //  JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_2nd");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class3==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_3rd='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_3rd='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_3rd='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_3rd='' where Day='"+Day3+"'and Serial_no=4");
                        
                      //  JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_3rd");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class4==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_4th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_4th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_4th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_4th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_4th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class5==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_5th='' where Day='"+Day3+"' and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_5th='' where Day='"+Day3+"' and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_5th='' where Day='"+Day3+"'and  Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_5th='' where Day='"+Day3+"' and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_5th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class6==0)
                    {
                       // Data_State.execute("update Routine13__2_1__C1 set Class_6th='"+New_Value+"' where Class_6th='"+Old_Value+"'and Day='"+Day+"'");
                        Data_State.execute("update Routine13__2_1__C1 set Class_6th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_6th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_6th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_6th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_6th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class7==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_7th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_7th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_7th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_7th='' where Day='"+Day3+"'and Serial_no=4");
                        
                        JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_7th");
                        Update_Routine();;
                    }
                
                    if(Class8==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_8th='' where Day='"+Day3+"' and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_8th='' where Day='"+Day3+"' and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_8th='' where Day='"+Day3+"' and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_8th='' where Day='"+Day3+"' and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_8th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class9==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_9th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_9th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_9th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_9th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_9th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class10==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_10th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_10th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_10th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_10th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_10th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class11==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_11th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_11th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_11th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_11th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_11th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class12==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_12th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_12th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_12th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_12th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_12th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
                
                    if(Class13==0)
                    {
                        Data_State.execute("update Routine13__2_1__C1 set Class_13th='' where Day='"+Day3+"'and Serial_no=1");
                        Data_State.execute("update Routine13__2_1__C1 set Class_13th='' where Day='"+Day3+"'and Serial_no=2");
                        Data_State.execute("update Routine13__2_1__C1 set Class_13th='' where Day='"+Day3+"'and Serial_no=3");
                        Data_State.execute("update Routine13__2_1__C1 set Class_13th='' where Day='"+Day3+"'and Serial_no=4");
                        
                       // JOptionPane.showMessageDialog(null, " Data Deleted successfully from  "+Day3+"  Class_13th");
                        jLabel4.setVisible(false);
                        Update_Routine();
                    }
            
            */
        
    }
    
    
    private void textField_Teacher_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Teacher_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Teacher_NameActionPerformed

    /*
     * @param args the command line arguments
     */
    
    
    
    
    
    
    
     public  void connect()
    {
        
       try
        {
          //  String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
           // Class.forName(driver);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            
            String AccessFileName="D:/Razu's Document/SD-II ( LAB )/Routine7/src/routine7/LogInData";
            
            String db1 = "jdbc:odbc:DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + AccessFileName + ".accdb;";
            Data_Con = DriverManager.getConnection(db1, "", "");
            Data_State =Data_Con.createStatement();
            
            System.out.println("hii");
        }
        catch(Exception ex)
        {
            
        }
                         
    } 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Routine_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Routine_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Routine_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Routine_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Routine_Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button_Add_Data;
    private java.awt.Button button_Routine_Manage_Delete;
    private java.awt.Button button_Update;
    private javax.swing.JComboBox jComboBox1_Class_Number;
    private javax.swing.JComboBox jComboBox1_Day;
    private javax.swing.JComboBox jComboBox_Class_Number2;
    private javax.swing.JComboBox jComboBox_Data_Type;
    private javax.swing.JComboBox jComboBox_Day2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField textField_Course_Name;
    private javax.swing.JTextField textField_New_Value;
    private javax.swing.JTextField textField_Room_No;
    private javax.swing.JTextField textField_Teacher_Name;
    private javax.swing.JTextField textField_Time_to_Time;
    // End of variables declaration//GEN-END:variables
}
